### ISSUE TITLE
Board statistics 

### ISSUE THREAD

**Issue by HarshdipD** [HarshdipD/job-tracker#14]
Thinking of creating a 'tab' in the extension that shows easy stats of the Trello board.
More specifically, the number of items in all the lists.

## How to do it:
1. Use bootstrap's tab component, with the first tab as the form and second as stats.
2. Send GET requests and get the number of cards in each list of the board and display the number. More stats can be added as it seems fit.

**Comment by utkarsh4321** [comment]
Hi @HarshdipD can i work in this issue.

**Comment by HarshdipD** [comment]
@utkarsh4321  Please feel free to do it! Let me know if you need any help to understand setting it up or anything.

**Comment by utkarsh4321** [comment]
thanks, @HarshdipD when I will start working on it I will ping you. If I will face any problem.

**Comment by utkarsh4321** [comment]
Hii @HarshdipD can you please add hackertoberfest tag to this so it will count for hackertoberfest,.

**Comment by utkarsh4321** [comment]
Hii @HarshdipD setup is over can you please explain what you really want I understand the tab part in the first tab your form will show but in the second tab what to do I m unable to understand it properly. if you can explain to me it's lot helps me to do this task.

**Comment by HarshdipD** [comment]
@utkarsh4321 I've added the tag. The second tab will contain the number of cards in each list of the board.
Something like this:
Wishlist: 5 items 
Applied: 2 items
and so on. 
Let me know if that makes sense, and sorry for the delayed reply!

**Comment by utkarsh4321** [comment]
Ok thanks so here whislist is a card and that contains 5items.means I will
get whislist,applied on the api response.and on the basis of it I will
render card with there data on the card .Please tell me that I m right or
not.

**Comment by HarshdipD** [comment]
Wishlist is one of the list names in a Trello board. I recommend running the extension and seeing if it's creating a board for you with 8 lists. The second tab will send get requests to get number of cards in each of these lists and show it.
A template of these lists is shown in Readme.md

**Comment by utkarsh4321** [comment]
Hii @HarshdipD i added the tabs now which API I need to call to get the stats. Can you please tell me?

**Comment by HarshdipD** [comment]
> Hii @HarshdipD i added the tabs now which API I need to call to get the stats. Can you please tell me?
the Trello API to get board items

**Comment by utkarsh4321** [comment]
Hi, @HarshdipD can you give the link of it there are so many API the API below boards I need to check which one.

**Comment by HarshdipD** [comment]
@utkarsh4321  that's the whole issue, I may as well do it by myself haha. I can take care of this one if you're finding it difficult, you can try some other issue in the repo!

**Comment by utkarsh4321** [comment]
No I can do it no problem

**Comment by utkarsh4321** [comment]
Hii @HarshdipD this is my trello board can you tell me you want that list that highlighted into the image in the inside the wishlist.
![image](https://user-images.githubusercontent.com/30936607/96840243-d30d8e00-1467-11eb-8cd9-639cf9b511a2.png)

**Comment by utkarsh4321** [comment]
Hii @HarshdipD can you tell me that highlighted portion you want to see into the second tabs.
![trelloPro](https://user-images.githubusercontent.com/30936607/96840444-17009300-1468-11eb-862c-58017dae4b4c.png)

**Comment by HarshdipD** [comment]
@utkarsh4321 with context to this picture, the board statistics (second tab) will be:
```
Wishlist: 4 items
Applied: 0 items
inProgress: 0 items
Offer: 0 items
Rejected: 0 items
```


So you just have to get **number of cards** in each list and show them. Hope that makes sense.

**Comment by utkarsh4321** [comment]
Ok thanks

**Comment by utkarsh4321** [comment]
Hii @HarshdipD I implemented as you said can you see the video and tell is it right or not.

![image](https://user-images.githubusercontent.com/30936607/97080180-2eca4980-1617-11eb-813a-b5bababf84b6.png)

**Comment by utkarsh4321** [comment]
Hii I clone repo again but I m unable to authorize it's's telling invalid return URL.

**Comment by HarshdipD** [comment]
@utkarsh4321 let's move this discussion to the PR thread.
