### ISSUE TITLE
Allow ability to add an existing board

### ISSUE THREAD

**Issue by HarshdipD** [HarshdipD/job-tracker#18]
Title.
Currently, the extension creates a new board for the user. I want an option for the user to add their existing board if they want.
This can be done by letting users enter the URL of their board after the OAuth screen, and we can parse the ID and save it as board_id.

I would create a new issue that would let the user change their boards once set.

**Comment by Anca07** [comment]
I would like to work on this issue :)

**Comment by HarshdipD** [comment]
@Anca07  awesome! Please feel free to work on it and submit a PR.

**Comment by HarshdipD** [comment]
This might get a bit complicated, so here is how I see the process of it. Let me know if you have a better idea.

1. In the `board_missing` div, include another div of an input id that lets user paste their board. Text can be let us create a board for you or paste an existing board. The user gets to click only one button. As soon as one button is clicked make sure to disable everything else.
2. On hitting submit of the input field, parse and save the board_id on local storage and switch to `oauth_ok` div.

Let me know if this works!

**Comment by Anca07** [comment]
Hi @HarshdipD 

Thanks for the guidance, it was really helpful 😄 I was thinking of something like this for the layout.

The user has the option to create a new board, as it was before (selected by default):
![image](https://user-images.githubusercontent.com/18334788/96515996-f6b9b400-126e-11eb-90b4-b32611253574.png)

The user can choose to use an existing board, so he will be requested to fill in the board URL:
![image](https://user-images.githubusercontent.com/18334788/96515972-eacdf200-126e-11eb-823c-e866f381f714.png)


I also changed the text above and the button text from Create to Done, as it would make more sense.

Please let me know what you think of this 😄

**Comment by HarshdipD** [comment]
This is amazing! Please carry on with this!
