### ISSUE TITLE
Google Analytics for the extension

### ISSUE THREAD

**Issue by HarshdipD** [HarshdipD/job-tracker#20]
This is a good first issue for newcomers to get introduced to Google Analytics and capturing insights. 

## Task:
Capture activity of users like the number of times the extension is clicked, the 'Create card' button is pressed, and more. 

## How to do it:
Here are the official docs to get started: https://developer.chrome.com/extensions/tut_analytics
Anyone working on this issue is required to have their Google Analytics key, which should be created in a separate file (and added on .gitignore). Clear instructions on how to replicate the key as a variable are required in the pull request. 

In the production version, I'll add my own keys. 

Please message in this thread if you're interested before you start!

**Comment by Bhavesh27** [comment]
@HarshdipD Can you assign this to me. I can take this up.

**Comment by Bhavesh27** [comment]
@HarshdipD https://github.com/HarshdipD/job-tracker/pull/21 Added Google Analytics Tracking. Add Button Click Event and PageView Event.

**Comment by HarshdipD** [comment]
Thank you Bhavesh! I'll review the PR soon and add you!
