### ISSUE TITLE
Scrape LinkedIn pages to autofill form

### ISSUE THREAD

**Issue by HarshdipD** [HarshdipD/job-tracker#22]
This is a good first issue for people trying web scraping. If you're interested in this, please leave a comment in this thread and tag me if you have any follow up questions.

## Issue: 
Since LinkedIn is one of the primary websites for job search, getting the fields auto-fill will can save some clicks. Users will just have to choose the list and press the submit button!

![image](https://user-images.githubusercontent.com/31940194/96388626-1f12b700-1178-11eb-8d51-df8d7e854f68.png)

## Initial thought process:
- Get company name, location, and job position through web scraping (will this work with plain js?)
- Put those values in fields directly

If scraping the page requires additional permissions for the extension, please comment about it below.

**Comment by blee1710** [comment]
@HarshdipD 

Hi! I'd like to take this on. I've got something working at the moment, however it doesn't work when the job description has no image.
