### ISSUE TITLE
Delete existing lists

### ISSUE THREAD

**Issue by HarshdipD** [HarshdipD/job-tracker#25]
This is a good first issue for the introduction to Trello API.

When a user uses the extension for the first time, the extension creates a board for them with 5 lists:
1. Wishlist
2. Applied
3. In Progress
4. Offer
5. Rejected

However, Trello POST request for creating board has 3 lists that are automatically created - To do, Done, Doing.

We need to somehow delete these existing lists before we send a POST request to create the above desired 5 lists. I'm guessing the easiest way is to send a delete request but there might be a better way within API docs.
 
If you're interested in this issue, please comment below before you fork and start working!

**Comment by derekdkim** [comment]
Mind if I try my hand at this issue?

**Comment by HarshdipD** [comment]
@derekdkim  go ahead!

**Comment by derekdkim** [comment]
Hi there, it looks like there wasn't a need to delete it in the first place. There's an option to just not add the default lists when you post the board.
