### ISSUE TITLE
Form validation

### ISSUE THREAD

**Issue by HarshdipD** [HarshdipD/job-tracker#28]
This is a good first issue to validate the input form before sending an API call.

**To Reproduce**
1. Click the extension
2. Enter fields but don't choose any list
3. Click 'Add to Trello' button
4. Error is shown and refreshing it means all info is gone

**Expected behavior**
The screen should tell users to choose a list before sending the POST request, preserving the data.

**Further enhancement**
The error div should have a link to hide the error div and display the original div again, in case the error is not related to form invalidation.

**Comment by slaterslater** [comment]
Can I be assigned to this? I'd like to give it a try
