### ISSUE TITLE
Console errors from Trello OAuth

### ISSUE THREAD

**Issue by HarshdipD** [HarshdipD/job-tracker#30]
**Describe the bug**
Not necessarily a bug, but I did not spend a lot of time working on the Trello OAuth. It works perfectly, but following different tutorials, I might have added code that's not needed, which shows me errors.

**To Reproduce**
1. When using the extension for the first time, it directs you to the settings page, where you authorize Trello.
2. After this step, errors can be seen in the console.

**Expected behavior**
No errors on the console

**Screenshots**
![image](https://user-images.githubusercontent.com/31940194/96787576-fda40c00-13bf-11eb-8ee4-dbc03c7f8694.png)
![image](https://user-images.githubusercontent.com/31940194/96787358-971eee00-13bf-11eb-84d1-9368a001e6bd.png)

**Additional context**
This does not give any actual errors to the user, but I'd like to see these errors from console gone. If you're interested in solving this, please comment on this thread. Please make sure to describe your process in solving this issue in the pull request so we can learn too!

Also, the last 2 errors in the screenshot above were introduced by #23, it should be easy to fix so no need for a new issue.

**Comment by HarshdipD** [comment]
Update: `sendResponse` error has been removed by simply removing the function from `popup.js`, I don't think that breaks anything. Only 1 error is left.

**Comment by dummyprogrammer** [comment]
Hi @HarshdipD ! Can i work on this issue?  Thanks

**Comment by HarshdipD** [comment]
@dummyprogrammer  feel free to!

**Comment by Prakort** [comment]
@HarshdipD there is no Trello auth error appeared
