### ISSUE TITLE
Geocoding for location 

### ISSUE THREAD

**Issue by Prakort** [HarshdipD/job-tracker#36]
**Is your feature request related to a problem? Please describe.**
It's more convenient for use if there is a list of auto suggested location

**Describe the solution you'd like**.
Using Google Geocoding API to get the result of the entered input

**Describe alternatives you've considered**
Hard coding the list of locations(not preferred)

**Additional context**
N/A

**Comment by sooster910** [comment]
Hi  👋  @HarshdipD . Can I work with this?

**Comment by HarshdipD** [comment]
@sooster910  feel free to! Thanks!

**Comment by sooster910** [comment]
Hi @HarshdipD 👋 ,   I kept getting error which app crashed after I clicked allow Trello's auth.  
![Screen Shot 2020-10-29 at 12 03 42 PM](https://user- images.githubusercontent.com/26635607/97520525-cc8a9380-19de-11eb-837e-b198c2c6ee80.png)
Any ideas to solve ? Thanks 😄

**Comment by HarshdipD** [comment]
@sooster910 the app should not crash. It displays this error on the console, I am aware of that, but it doesn't affect the extension in any way. After you authorize, you should click on the extension from the chrome and it should work:
![image](https://user-images.githubusercontent.com/31940194/97547099-c75c2300-19a3-11eb-9f63-833cad1725d9.png)

**Comment by sooster910** [comment]
@HarshdipD  Thanks a lot!

**Comment by HarshdipD** [comment]
@sooster910  no problem! Also, I went through your GitHub and your front end skills are very impressive! Please feel free to work on making the styling better if you'd like to while working on this issue! I didn't spend a lot of time on the front-end haha

**Comment by HarshdipD** [comment]
@sooster910  this is amazing! Yes, the autocomplete to suggest locations, which is what you have done! It looks great, I think you can create a PR :)

**Comment by Prakort** [comment]
@sooster910 thanks for doing this ticket. Feel free to make a pr.
