### ISSUE TITLE
Firefox extension

### ISSUE THREAD

**Issue by HarshdipD** [HarshdipD/job-tracker#40]
I've received a lot of requests for this extension to be available in the Firefox web browser. 
This sounds like an easy task; I think there are just a few API functions names that need to be renamed. 

If you're interested in this issue, please let me know! This would be of huge help to Firefox users!

## How to start:
We'll have the same repository for both extensions, so one of doing this would be to create two folders, one of Chrome extension code and the other for Firefox. If it's possible to keep the same code with if-else statements, that would be highly preferred of course. Having same code base would also mean new features wouldn't have to be written twice.

I have not spent a lot of time reading Firefox's docs, but it took me a maximum of 20 minutes to understand how a Chrome extension works so this should be fairly easier since all the code is the same.

**Comment by Prakort** [comment]
@HarshdipD I got this.
